version: "3.8"
services:
  queuebot:
    image: $CI_REGISTRY_IMAGE:$DOCKER_TAG
    environment:
      DATABASE_ENGINE: postgresql
      DATABASE_NAME: delaybot
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_USER: delaybot
      DATABASE_PASSWORD: delaybot
    ports:
      - "8615:8000"
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: "delaybot"
      POSTGRES_USER: "delaybot"
      POSTGRES_PASSWORD: "delaybot"
    volumes:
       - postgres:/data/postgres
    expose:
      - 5432
volumes:
  postgres: