"""add user's photo_url field

Revision ID: 4b761e125df8
Revises: b2dbda21d136
Create Date: 2025-05-14 13:00:15.766306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b761e125df8'
down_revision: Union[str, None] = 'b2dbda21d136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('photo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'photo_url')
    # ### end Alembic commands ###
