"""add sharing system

Revision ID: f67af12c54cc
Revises: eea023588eb6
Create Date: 2025-04-24 22:10:21.665641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import advanced_alchemy.types.datetime


# revision identifiers, used by Alembic.
revision: str = 'f67af12c54cc'
down_revision: Union[str, None] = 'eea023588eb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue_permission',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('queue_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('can_manage', sa.Boolean(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['queue.id'], name=op.f('fk_queue_permission_queue_id_queue'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_queue_permission_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_queue_permission')),
    sa.UniqueConstraint('queue_id', 'user_id', name='uq_queue_user')
    )
    op.create_index('ix_queue_permission_queue_id', 'queue_permission', ['queue_id'], unique=False)
    op.create_index('ix_queue_permission_user_id', 'queue_permission', ['user_id'], unique=False)
    op.create_table('queue_share',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('queue_id', sa.BigInteger(), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('can_manage', sa.Boolean(), nullable=True),
    sa.Column('expires_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['queue.id'], name=op.f('fk_queue_share_queue_id_queue'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_queue_share'))
    )
    op.create_index(op.f('ix_queue_share_token'), 'queue_share', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_queue_share_token'), table_name='queue_share')
    op.drop_table('queue_share')
    op.drop_index('ix_queue_permission_user_id', table_name='queue_permission')
    op.drop_index('ix_queue_permission_queue_id', table_name='queue_permission')
    op.drop_table('queue_permission')
    # ### end Alembic commands ###
