"""advanced

Revision ID: f712d6aac0ef
Revises: 7d1eac752080
Create Date: 2025-03-13 22:46:57.099830

"""
from typing import Sequence, Union
import advanced_alchemy.types.datetime
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f712d6aac0ef'
down_revision: Union[str, None] = '7d1eac752080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('title', sa.Text(), nullable=True))
    op.alter_column('chat', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('chat', 'name')
    op.alter_column('queue', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('queue', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'updated_at',
               existing_type=advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user', 'created_at',
               existing_type=advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('queue', 'updated_at',
               existing_type=advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('queue', 'created_at',
               existing_type=advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('chat', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('chat', 'updated_at',
               existing_type=advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat', 'created_at',
               existing_type=advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('chat', 'title')
    # ### end Alembic commands ###
