name: Tests
on:
  push:
    branches: [ "master" ]
  release:
    types: [published, edited]
  workflow_dispatch:
    inputs:
      version:
        default: latest
        description: Tag you want to release.
        required: true
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run tests
      run: docker-compose -f ./docker-compose.tests.yaml run tests